#!/usr/bin/env ruby

require "ctf-tools"

encrypted = open("encrypted.txt").read.chomp.to_i
n, p, q, e, d = open("private.txt").readlines.map{|x| x[/\d+/].to_i}

pt = RSA.decrypt(encrypted, n: n, d: d)
puts pt.to_s_binary
