#!/usr/bin/env ruby

unless ARGV.size == 1 and ARGV[0].size == 40
  STDERR.puts "Usage: #{$0} 'flag{...}'"
  STDERR.puts "Flag must be exactly 40 characters"
  exit 1
end

key = ARGV[0]
len = 40

hit = {}
ary = (0...len).map{|i| [key[i].ord, "p#{i}"] }
expected = []

# p ary

40.times do
  c, ci = ary[7]
  expected << c
  hit[ci] = true
  # shuffle
  ary = (0...len).map{|i|
    ary[(21 * i + 17) % len]
  }
  # shift
  ary = (0...len).map{|i|
    c, ci = ary[i]
    [(c * 7 + i * 19) & 255, ci]
  }
end

p expected
# p hit
